### ISSUE TITLE
Pending issues to release the configurator as an NW.js app

### ISSUE THREAD

**Issue by fiam** [iNavFlight/inav-configurator#234]
- [x] Fix drag and drop in the OSD tab. It fails on NW.js 0.24.4 (fixed in #237)
- [x] Add an update mechanism. Can be as simple as showing a dialog to the user when a new version of the configurator is released.
- [x] The app always launches with a 1024px window, which doesn't show tab names. Consider making the app bigger by default or, at least, save the last used size/position. We need to take into account devices with screens 1024px wide, so we can't just make the app require 1200px.
- [x] Build easily redistributable package for Windows (fixed in #235)
- [x] Build easily redistributable package for macOS (fixed in #235)
- [x] Build easily redistributable package for Linux

**Comment by fiam** [comment]
I think this can be closed. The remaining points have been fixed by @Afinogen .
